// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"go-kratos-mcp-demo/api/gen/go/conf"
	"go-kratos-mcp-demo/internal/server"
	"go-kratos-mcp-demo/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(logger log.Logger, recommendConfig *conf.RecommendConfig) (*kratos.App, func(), error) {
	recallService := service.NewRecallService(logger, recommendConfig)
	rankService := service.NewRankService(logger, recommendConfig)
	filterService := service.NewFilterService(logger, recommendConfig)
	recommendService := service.NewRecommendService(logger, recallService, rankService, filterService)
	mcpServer := server.NewMcpServer(logger, recommendService)
	httpServer := server.NewRESTServer(logger, recommendService)
	app := newApp(logger, mcpServer, httpServer)
	return app, func() {
	}, nil
}
